%global debug_package %{nil}

Name:           connectome-workbench
Version:        2.1.0
Release:        1%{?dist}
Summary:        HCP Visualization and Discovery Tool

License:        GPL-2.0-only
URL:            https://github.com/Washington-University/workbench
Source0:        %{name}-%{version}.tar.gz

BuildRequires:  cmake
BuildRequires:  gcc-c++
BuildRequires:  qt5-qtbase-devel
BuildRequires:  qt5-qtsvg-devel
BuildRequires:  qt5-qtxmlpatterns-devel
BuildRequires:  mesa-libGL-devel
BuildRequires:  mesa-libGLU-devel
BuildRequires:  glm-devel
BuildRequires:  zlib-devel
BuildRequires:  libxml2-devel
BuildRequires:  git-core
# Xvfb is required to run GUI tests in a headless build environment
BuildRequires:  xorg-x11-server-Xvfb

Requires:       qt5-qtbase
Requires:       qt5-qtsvg
Requires:       qt5-qtxmlpatterns

%description
Connectome Workbench is an open source visualization and discovery tool used 
to map neuroimaging data, especially data generated by the Human Connectome 
Project.

%prep
%autosetup -n workbench-%{version}

# FIX 1: Add missing header for Fedora 43 / GCC 15+
sed -i '/#include <memory>/a #include <cstdint>' src/Common/CaretRgb.h

# FIX 2: Fix Qt5 header include
sed -i 's/#include <QtEnvironmentVariables>/#include <QtCore>/g' src/Common/WorkbenchInstallationAssistant.cxx

# FIX 3: Fix Qt MOC linking error
if ! grep -q "CaretFileDialog.moc" src/GuiQt/CaretFileDialog.cxx; then
    echo '#include "CaretFileDialog.moc"' >> src/GuiQt/CaretFileDialog.cxx
fi

%build
cd src
# Relax security checks and allow legacy C++ conversions (char* <-> unsigned char*)
export CFLAGS="%{optflags} -Wno-error=format-security"
export CXXFLAGS="%{optflags} -Wno-error=format-security -fpermissive"

%cmake \
    -DWORKBENCH_USE_QT5=TRUE \
    -DWORKBENCH_USE_OPENMP=TRUE \
    -DWORKBENCH_CHECK_FOR_UPDATES=FALSE \
    -DWORKBENCH_USE_SYSTEM_FTGL=FALSE \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo \
    -DCMAKE_CXX_STANDARD=17 \
    -DCMAKE_AUTOMOC=ON \
    -DCMAKE_INCLUDE_CURRENT_DIR=ON

%cmake_build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}%{_bindir}
mkdir -p %{buildroot}%{_datadir}/applications
mkdir -p %{buildroot}%{_datadir}/icons/hicolor/128x128/apps

cd src

# Install Binaries
find %{_vpath_builddir} -name "wb_command" -type f -exec install -m 755 {} %{buildroot}%{_bindir}/ \;
find %{_vpath_builddir} -name "wb_view" -type f -exec install -m 755 {} %{buildroot}%{_bindir}/ \;

# Install Desktop Entry
cat > %{buildroot}%{_datadir}/applications/wb_view.desktop <<EOF
[Desktop Entry]
Name=Connectome Workbench
Comment=HCP Neuroimaging Visualization
Exec=wb_view
Icon=wb_view
Terminal=false
Type=Application
Categories=Science;MedicalSoftware;
EOF

# Install Icon
find ../icons -name "workbench.png" -exec install -m 644 {} %{buildroot}%{_datadir}/icons/hicolor/128x128/apps/wb_view.png \;

%check
# Run the internal test suite
# We use xvfb-run because wb_view tests require a display
cd src
%if 0%{?fedora} >= 35
    # Force CTest to look in the correct build directory
    cd %{_vpath_builddir}
    xvfb-run -a ctest --output-on-failure
%endif

%files
%license LICENSE
%doc README.md
%{_bindir}/wb_command
%{_bindir}/wb_view
%{_datadir}/applications/wb_view.desktop
%{_datadir}/icons/hicolor/128x128/apps/wb_view.png

%changelog
* Sun Jan 04 2026 Morgan Hough <morgan.hough@gmail.com> - 2.1.0-1
- Initial RPM release for Connectome Workbench v2.1.0
